#!/data/data/com.termux/files/usr/bin/bash
# Installer Tools V.1
# Author Mr.T4K0Y4K1
# reedit ? izin .)
# https://facebook.com/dhnl28
clear

blue='\e[0;34'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'


echo -e $yellow" __                ___    ___"                          
echo -e $yellow"/\ \              /\_ \  /\_ \"                         
echo -e $yellow"\ \ \         __  \//\ \ \//\ \      __   _ __   ____"  
echo -e $white"  \ \ \  __  /'__`\  \ \ \  \ \ \   /'__`\/\`'__\/',__\" 
echo -e $white"   \ \ \L\ \/\ \L\.\_ \_\ \_ \_\ \_/\  __/\ \ \//\__, `\"
echo -e $white"    \ \____/\ \__/.\_\/\____\/\____\ \____\\ \_\\/\____/"
echo -e "black"     \/___/  \/__/\/_/\/____/\/____/\/____/ \/_/ \/___/"
                                                    



echo -e $red"Lallers Tools V.1"
echo -e $white"Authore : Mr.T4K0Y4K1"
echo -e $red" [01] Nmap"
echo -e $red" [02] FbBrute"
echo -e $red" [03] Weeman"
echo -e $red" [04] webdav"
echo -e $red" [05] SqlMap"
echo -e $red" [06] WpScan"
echo -e $red" [07] Nikto"
echo -e $red" [08] Joomscan"
echo -e $red" [09] Metasploit"
echo -e $red" [10] Admin Finder"
echo -e $red" [11] Ngrok"
echo -e $red" [12] SqlMate"
echo -e $red" [13] Bing dorker"
echo -e $red" [14] Bot Deface"
echo -e $red" [15] Bot Komen FB"
echo -e $red" [16] Gmail Brute Froce"
echo -e $red" [17] IPGeolocation"
echo -e $red" [18] SpiderBOT"
echo -e $red" [19] Creater Virus"
echo -e $red" [20] Hunner FrameWork"
echo -e $red" [00] exit"
read -p  "{Mr.T4K0Y4K1}- " act;

if [ $act = 01 ] || [ $act = 01 ]
then
clear
echo -e $yellow" Installing Nmap"
s/leep 1
apt update && apt upgrade
apt install nmap
nmap -help
echo -e $yellow"selesai"
fi

if [ $act = 02 ] || [ $act = 02 ]
then
clear
echo -e $cyan" Installing FbBrute"
sleep 1
apt update && apt upgrade -y
apt install python2
apt install python2-dev
apt install wget
pip2 install mechanize
mkdir FbBrute
cd ~/fbbrute
wget https://pastebin.com/raw/aqMBt2xA -o fbbrute.py
wget http://override.waper.co/files/password.apk
mv password.apk password.txt
chmod 777 fbbrute.py
cd ~/
echo -e $yellow"Selesai"
fi

if [ $act = 03 ] || [ $act = 03 ]
then
clear
echo -e $cyan" Installing Weeman"
sleep 1
apt update && apt upgrade -y
pkg install git
apt install python2
git clone https://github.com/samyoyo/weeman
cd ~/weeman
pip2 install beautifulsoup
pip2 install bs4
cd ~/
echo -e $green"Selesai"
fi

if [ $act = 04 ] || [ $act = 04 ]
then
clear
echo -e $cyan" Installing Webdav"
sleep 1
apt update && apt upgrade -y
apt install python2
pip2 install urllib3 chardet certifi idna requests
apt install openssl curl
pkg libcurl
mkdir webdav
cd ~/webdav
wget https://pastebin.com/raw/HnVyQPtR -o webdav.py
chmod 777 webdav.py
cd ~/
echo -e $green"Selesai"
fi

if [ $act = 05 ] || [ $act = 05 ]
then
clear
echo -e $cyan" Installing SqlMap"
sleep 1
apt-get update
apt-get install python2
apt-get install git
git clone https://github.com/sqlmapproject/sqlmap.git
cd~/
echo -e $green"Selesai"
fi

if [ $act = 06 ] || [ $act = 06 ]
then
clear
echo -e $cyan" Installing WpScan"
sleep 1
apt update && apt upgrade -y
apt install ruby
apt install curl
apt install git
git clone https://github.com/wpscanteam/wpscan
cd ~/wpscan
gem install bundle
bundle config build.nokogiri --use-system-libraries
bundle install
ruby wpscan.rb --update
cd ~/
echo -e $green"Selesai"
fi

if [ $act = 07 ] || [ $act = 07 ]
then
clear
echo -e $cyan" Installing Nikto"
sleep 1
pkg update && pkg upgrade -y
pkg install perl
pkg install git
git clone https://github.com/sullo/nikto
echo -e $green"Selesai"
fi

if [ $act = 08 ] || [ $act = 08 ]
then
clear
echo -e $cyan" Installing Joomscan"
sleep 1
apt update && apt upgrade -y
apt install git
apt install perl
git clone https://github.com/rezasp/joomscan.git
echo -e $green"Selesai"
fi

if [ $act = 09 ] || [ $act = 09 ]
then
clear
echo -e $cyan" Installing Metasploit"
sleep 1
apt update && apt upgrade -y
apt install git
apt install wget
wget https://raw.githubusercontent.com/verluchie/termux-metasploit
chmod 777 install.sh
echo -e $green"Selesai"
fi

if [ $act = 10 ] || [ $act = 10 ]
then
clear
echo -e $cyan" Installing Admin Finder"
sleep 1
apt update && apt upgrade -y
apt install git
apt install python2
git clone https://github.com/the-c0d3r/admin-finder.git
echo -e $green"Selesai"
fi

if [ $act = 11 ] || [ $act = 11 ]
then
clear
echo -e $cyan" Installing Ngrok"
sleep 1
apt install wget
mkdir ngrok
cd ~/ngrok
wget https://bin.equinox.io/c/4VmDzA7iahb/ngrok-stable-linux-arm.z$
unzip ngrok-stable-linux-arm.zip
cd ~/
echo -e $green"Selesai"
fi

if [ $act = 12 ] || [ $act = 12 ]
then
clear
echo -e $cyan" Installing SqlMate"
sleep 1
apt update && apt upgrade
apt install git python python2
git clone https://github.com/UltimateHackers/sqlmate.git
cd ~/sqlmate
pip2 install -r requirements.txt
pip2 install urlparse2
cd ~/
echo -e $green"Selesai"
fi

if [ $act = 13 ] || [ $act = 13 ]
then
clear
echo $cyan" Installing Bing dorker"
sleep 1
apt update && apt upgrade -y
apt install wget
apt install php
mkdir bing
cd ~/bing
wget https://pastebin.com/raw/tjQY6Tsg -O dorker.php
cd ~/
echo -e $green"Selesai"
fi

if [ $act = 14 ] || [ $act = 14 ]                                  then
clear                                                              echo -e $cyan"Installing Bot Deface..."
sleep 1
apt update && apt upgrade -y
apt install git
apt install perl
git clone https://github.com/Moham3dRiahi/XAttacker
cd XAttacker.pl
chmod 777 XAttacker.pl
echo -e $green"Selesai"
fi

if [ $act = 15 ] || [ $act = 15 ]
then
clear
echo -e $cyan"Installing Bot Auto Komen Facebook"
sleep 1
pkg update && pkg upgrade-y
pkg install git
pkg istall python2
pip2 install mechanize
git clone https://github.com/Senitopeng/Botkomena.git
cd ~/
echo $green"Selesai"
fi

if [ $act = 16 ] || [ $act = 16 ]
then
clear
echo -e $cyan"Installing Gmail BruteFroce"
sleep 1
apt update && apt upgrade -y
apt install git
git clone https://github.com/rand0m1ze/ezsploit
sleep 1
echo -e $red"Please wait ......"
sleep 1
echo -e $green"Sukses"
fi

if [ $act = 17 ] || [ $act = 17 ]
then
clear
echo -e $cyan"Installing IPGeolocation"
sleep 1
apt update && apt upgrade
apt install git
apt install python2
git clone https://github.com/maldevel/IPGeolocation.git
cd IPGeolocation
chmod +x ipgeolocation.py
pip2 install -r requirements.txt
sleep 1
echo $green"Selesai"
fi

if [ $act = 18 ] || [ $act = 18 ]
then
clear
echo -e $cyan"Installing SpiderBOT"
sleep 1
apt update && apt upgrade
apt install git
apt install php
git clone https://github.com/Cvar1984/SpiderBot.cgi
echo -e $green"Selesai"
fi

if [ $act = 19 ] || [ $act = 19 ]
then
clear
echo -e $yellow"Installing CreaterVirus"
sleep 1
termux-setup-storage
cd storage
apt update && apt upgrade -y
apt install python2
gem install lolcat
apt install figlet
apt install git
pip2 insyall mechanize
git clone https://github.com/viruz09/CreaterVirus.git
echo -e $red"loading......"
sleep 1
echo -e $yellow"Selesai"
fi

if [ $act = 20 ] || [ $act = 20 ]
then
echo -e $yellow"Installing Hunner FrameWork"
sleep 1
apt update && apt upgrade -y
apt install git
apt install python-dev
git clone https://github.com/b3-v3r/Hunner.git
cd ~/Hunner
chmod +x hunner.py
cd ~/
echo -e $yellow"Selesai"
fi

if [ $act = 00 ] || [ $act = 00 ]
then
echo -e $yellow"Terima Kasih Telah Menggunakan Tools Ini"
sleep 1
echo -e $yellow"Contac Me:"
sleep 1
echo -e $yellow"https://facebook.com/dhnl28"
sleep 1
exit
echo -e $yellow"Thanks Mastah"
fi
